apiVersion: apps/v1
kind: Deployment
metadata:
  name: oracleapp1-deployment
  labels:
    app: oracleapp1
spec:
  replicas: 1  # You can change this if you want to scale
  selector:
    matchLabels:
      app: oracleapp1
  template:
    metadata:
      labels:
        app: oracleapp1
    spec:
      containers:
        - name: oracleapp1-container
          image: oracle-app1:latest  # Replace with your image 
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9999   # Replace with your app's exposed port
          env:
            - name: LD_LIBRARY_PATH
              value: "/opt/oracle/instantclient_21_13"
            - name: PATH
              value: "/opt/oracle/instantclient_21_13:$PATH"
          
